config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :posts, except: [:edit, :update] do
    get :search, on: :collection
  end

  resources :comments, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    delete "sign_out", to: "users/sessions#destroy"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 30

  belongs_to :user
  has_many :comments,         dependent: :destroy
  has_many :posts_categories, dependent: :destroy
  has_many :categories,       through: :posts_categories

  validates :title,   presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :user_id, presence: true

  scope :from_new_to_old, -> { includes(:user).order(created_at: :desc) }

  scope :search_by, -> (word) do
    eager_load(:comments).where(
      "posts.title LIKE :word
        OR posts.content LIKE :word
        OR comments.content LIKE :word",
      word: "%#{sanitize_sql_like(word)}%",
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "スレッドを作成しました！"
      redirect_to @post
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).page(params[:page])
    if current_user.present?
      @comment = current_user.comments.build
    end
  end

  def destroy
    post = current_user.posts.find_by(id: params[:id])
    if post
      post.destroy
      flash[:success] = "スレッドを削除しました。"
    end
    redirect_to root_path
  end

  def search
    @search_word = params[:search]
    @posts = Post.search_by(@search_word).from_new_to_old.page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/views/posts/_comment_form.html.erb
<% if current_user.present? %>
  <div class="comment_form p-3">
    <div class="mb-2"><strong>レスを投稿</strong></div>
    <%= form_with(model: comment, local: true) do |f| %>
      <%= render "shared/error_messages", object: comment %>
      <%= f.hidden_field :post_id, value: post.id %>
      <div class="field mb-2">
        <%= f.text_area :content, placeholder: "内容", cols:40 , rows:10, class: "form-control" %>
      </div>
      <div class="actions mb-2">
        <%= f.submit "投稿", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% user = post.user %>
<div class="post card mb-3" id="post_<%= post.id %>">
  <div class="card-body">
    <div class="card-title">
      <h3><%= post.title %></h3>
    </div>
    <hr>
    <%= auto_link(simple_format(h(post.content), {}, sanitize: false, wrapper_tag: "div"))%>
  </div>
  <div class="card-text">
    <div class="post_details text-right pr-2">
      <small class="text-muted">
        <span class="mr-1 user_card_name"><%= user.nickname %>★</span>
        <span class="mr-1">
          <% if current_path?(post_path(post)) %>
            レス：<%= post.comments.count %>件
          <% else %>
            <%= link_to "レス：#{post.comments.count}件", post_path(post) %>
          <% end %>
        </span>
        <span class="mr-1"><%= post.created_at %></span>
        <% if current_user?(user) %>
          <span class="mr-1">
            <%= link_to "スレッドを削除", post, method: :delete, data: {confirm: "本当に削除しますか？"}, class: "text_delete" %>
          </span>
        <% end %>
      </small>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<% provide(:title, "スレッド投稿") %>
<h2>スレッド投稿</h2>
<%= form_with(model: @post, local: true) do |f| %>
  <%= render "shared/error_messages", object: @post %>
  <div class="field mb-2">
    <%= f.label :title %><br />
    <%= f.text_field :title, placeholder: "タイトル（30文字以内）", class: "form-control" %>
  </div>
  <div class="field mb-2">
    <%= f.label :content %><br />
    <%= f.text_area :content, placeholder: "内容", cols:40 , rows:12, class: "form-control" %>
  </div>
  <div class="actions mb-2">
    <%= f.submit "投稿", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/search.html.erb
<% provide(:title, @search_word) %>
<article class="main_section">
  <div class="card mb-3">
    <div class="card-header search_word">
      <h5>検索ワード：<%= @search_word %></h5>
    </div>
  </div>
  <% if @posts.present? %>
    <%= render "shared/posts_list_with_paginate", posts: @posts %>
  <% else %>
    <div class="p-3">スレッドが見つかりません。</div>
  <% end %>
</article>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="main_thread mb-3">
  <%= render "posts/post", post: @post %>
</div>
<div class="comments_field">
  <div class="mb-3"><%= paginate @comments %></div>
  <hr>
  <%= render partial:"comments/comment", collection: @comments, as: :comment %>
  <div class="mb-3"><%= paginate @comments %></div>
  <%= render "posts/comment_form", post: @post, comment: @comment %>
</div>