config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :posts, except: [:edit, :update] do
    get :search, on: :collection
  end

  resources :comments, only: [:create, :destroy]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    delete "sign_out", to: "users/sessions#destroy"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_flash_messages.html.erb
<div class="flash_message mt-2">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type} container")%>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Yama_ch", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "投稿", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ユーザ編集", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <%= form_with url: search_posts_path, method: :get, local: true, class: "search_form form-inline my-2 my-lg-0" do |f| %>
        <%= f.text_field :search, class:"form-control mr-sm-2", placeholder:"検索ワードを入力", type: "search" %>
        <%= f.submit "検索", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/default" %>
    <%= render "layouts/shim" %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container wrapper">
      <%= render "layouts/flash_messages" %>
      <div class="push mb-4"></div>
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>